export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Applications } from './Applications'
export { default as Footer } from './Footer'
export { default as Navbar } from './Navbar'
export { default as SubFooter } from './SubFooter'
